---
title: "Entry Level R Studio - Data importation, descriptive analysis, preprocessing, regression analysis, time series and forecasting"
author: "Markovska81"
date: "26/06/2019"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Libraries Used

library(readr)
library(psych)
library(tidyr)
library(dplyr)
library(MVN)
library(mvnTest)
library(car)
library(mvoutlier)
library(TSA)
library(tseries)
library(forecast)
library(rcompanion)
```


```{r}
# Step 1 - the url for the online csv file
url <- "http://www.fertilitydatasheet.org/download/files/Data_box_5_Immigrant_fertility.csv"
```


```{r}
# Step 2 - install and load readr
#install.packages("readr")
library(readr)
```

```{r}
# Step 3 - use read.csv to import dataset
dataset <- read.csv(url, stringsAsFactors = FALSE)
```

```{r}
# Step 4 - view first 6 entrants of dataset
head(dataset)
```

```{r}
# Step 5 - check the attributes of the dataset
attributes(dataset)
```

```{r}
# Step 6 - determine structure of dataset
str(dataset)
```

```{r}
# Step 7 - depict summary of dataset
summary(dataset)
```

```{r}
# Step 8 – descriptive statistics using the psych package
#install.packages(“psych”) 
library(psych)
describe(dataset)
```



```{r}
#Step 9 - change the name of the columns 3 and 4
colnames(dataset)[3]<-"TFR_foreign"
colnames(dataset)[4]<-"TFR_native"
head(dataset)
```

```{r}
# Step 10 - format variables from character to numeric
dataset$TFR_foreign <- as.numeric(dataset$TFR_foreign)
dataset$TFR_native <- as.numeric(dataset$TFR_native)
dataset$Overall_TFR <- as.numeric(dataset$Overall_TFR)
head(dataset)
```

```{r}
# Step 11 - install and load the tidyr and dplyr packages
#install.packages("tidyr")
#install.packages("dplyr")
library(tidyr)
library(dplyr)
```

```{r}
# Step 12 - check for NAs
sum(is.na(dataset))
```

```{r}
# Step 13 - omit all NA cases to get only complete cases
final <- na.omit(dataset)
head(final)
```

```{r}
# Step 14 -  determine nation state with highest Overall_TFR mean
final %>% group_by(Country) %>% summarise(mean_TFR = mean(Overall_TFR, na.rm = TRUE)) %>% arrange(desc(mean_TFR))
```

```{r}
# Step 15 - filter for Norway only
Norway <- final %>% dplyr::filter( Country == 'Norway')
head(Norway)
```


```{r}
# Step 16 - select variables for further analysis
selection <- Norway %>% dplyr::select(TFR_native, Overall_TFR, TFR_foreign)
head(selection)
```

```{r}
# Step 17 - Shapiro-Wilk normality test (univariate analysis of variables)
shapiro.test(selection$TFR_native)
shapiro.test(selection$Overall_TFR)
shapiro.test(selection$TFR_foreign)
```


```{r}
# Step 18 – determining multivariate normal distribution
#install.packages("MVN")
library(MVN)
library(mvnTest)
R.test(selection)
```
```{r}
selection
```

```{r}
# Step 19 – boxplot to look for outliers
#install.packages(“car”)
library(car)
Boxplot(selection, ylab = "TRF", main = "Boxplot of TRFs of Norwegian Women from 1990-2012", col = "pink")
```

```{r}
# Step 20 - Multivariate outlier detection
#install.packages("mvoutlier")
library(mvoutlier)
results <- MVN::mvn(data = selection, multivariateOutlierMethod = "quan", showOutliers = TRUE, univariatePlot = "histogram")
results
```

```{r}
# Step 21 - create a dataframe for each pair for further analysis
selection2 <- Norway %>% dplyr::select(Overall_TFR, TFR_foreign)
selection3 <- Norway %>% dplyr::select(TFR_native, TFR_foreign)
selection4 <- Norway %>% dplyr::select(TFR_native, Overall_TFR)
```

```{r}
# Step 22 – observe relationship between TFR_foreign and Overall_TFR
results2 <- MVN::mvn(data = selection2, multivariateOutlierMethod = "quan")
```

```{r}
# Step 23 – observe relationship between TFR_foreign and TFR_native
results3 <- MVN::mvn(data = selection3, multivariateOutlierMethod = "quan")
```


```{r}
# Step 24 – observe relationship between Overall_TFR and TFR_native
results4 <- MVN::mvn(data = selection4, multivariateOutlierMethod = "quan")
```

```{r}
# Step 25 – new normality test
R.test(selection4)
```


```{r}
#Step 26 - construct a scatterplot to determine causal relationship between TFR_native and Overall_TFR
plot(selection4, col='blue', pch=20, cex=2, main="Relationship between TFR_native & Overall_TFR", xlab="TFR_native", ylab="Overall_TFR")
```

```{r}
#Step 27 – fit the full model (lm function)
reg <- lm(Overall_TFR ~ ., data=selection4)
summary(reg)
```

```{r}
#Step 28 – fit the full model (olsrr function)
#install.packages("oslrr")
library(olsrr)
ols_regress(reg)
```

```{r}
#Step 29 - F-critical value 
qf(0.95, 1, 21)
# 95% confidence, 2 sided
abs(qt(0.05/2, 21)) 
# actual 2-sided values
qt(c(.025, .975), df=23-2)
```


```{r}
# Step 30 - Linearity
#R squared value
summary(reg)$r.squared
#residual Vs fitted values
plot(reg, 1)
```

```{r}
# Step 31 - Normality
shapiro.test(reg$residuals)
```

```{r}
# Step 32 - Homoscedasticity
ncvTest(reg)
```


```{r}
# Step 33 – No autocorrelation
durbinWatsonTest(reg)
```


```{r}
# Step 34 – Check for outliers in regression model
ols_plot_cooksd_bar(reg)
```


```{r}
# Step 35 – select Period and TFR_native
#install.packages("TSA")
library(TSA)
Norway_TS <- Norway %>% dplyr::select(Period, TFR_native)
head(Norway_TS)
```


```{r}
#Step 36 - Check class
class(Norway_TS)
```

```{r}
#Step 37 - convert to time series
tsmodel <- ts(as.vector(Norway_TS$TFR_native), start=1990, end=2012, frequency = 1) 
```

```{r}
#Step 38- check class after converting to ts format
class(tsmodel)
tsmodel
```

```{r}
# Step 39 - Plot series for descriptive analysis 
plot(tsmodel, ylab = "TFR", main = "TFR for Native-Born Norwegian Women from 1990 to 2012", type = "o")
```

```{r}
# Step 40 - Scatterplot ofconsecutive years
plot(y=tsmodel,x=zlag(tsmodel),ylab = "TFR_native", xlab = "Previous years' TFR_native", main="TFR_native vs Previous Years' TFR_native")
```

```{r}
# Step 41 - Determining correlation  
y = tsmodel 
x = zlag(tsmodel) 
index = 2:length(x) 
cor(y[index],x[index]) 
```


```{r}
# Step 42 - determining stationary status
#install.packages(“tseries”)
library(tseries)
adf.test (tsmodel)
kpss.test(tsmodel)
```

```{r}
#Step 43 – linear regression model
model1<-lm(tsmodel~time(tsmodel))
summary(model1)
```

```{r}
# Step 44 – line of best fit
plot(tsmodel, type = "o")
abline(model1,lty=2,col="red")
```

```{r}
# Step 45 - Quadratic model
t = time(tsmodel)
t2 = t^2
model2 = lm(tsmodel~t + t2)
summary(model2)
```


```{r}
# Step 46 – Plot of Quadratic curve
plot(tsmodel,type='o',ylab='TFR_native', main="Quadratic Model Curve to TFR_native")
points(t,predict.lm(model2), type="l", lty=2,col="red")
```


```{r}
# Step 47 – best model via automated forecasting
library(forecast)
ets(tsmodel)
```

```{r}
# Step 48 - forecast to 2020
fit <- ses(tsmodel, h=8)
summary(fit)
```


```{r}
# Step 49 - plot of forecasts to 2020
plot(fit)
```


```{r}
# Step 50  - Autocorrelation, Residuals over time, Box test
checkresiduals(fit, plot = TRUE)
```


```{r}
# Step 51 - Normality of residuals
shapiro.test(fit$residuals)
```

